### ISSUE TITLE
sf2tab.c doesn't save all the state

### ISSUE THREAD

**Issue by rdebath** [catseye/Dipple#1]
When it saves the state it saves the Program counter and the bits currently in the array.
However, the current cell pointer is also part of the machine state so the program is detecting a hang when, in fact, there isn't one because the two states differ by the position of the pointer.

**Comment by cpressey** [comment]
You are correct.  If you think https://github.com/catseye/Dipple/commit/30385e29f3771cd6138737be06b96d539e9ac797 fixes it (seems simple enough, but I haven't tested it,) please close this issue.  Thanks.

**Comment by rdebath** [comment]
Looks good, my test works correctly...

``` smallfuck
[*]*[*>[>]*<[*<]*]
```

It doesn't work with a 16 cell tape though ... I don't expect there's much to do about that, except waiting for a few days ... at least  :-)
